version: "3.9"

services:
  database:
    image: postgres
    container_name: database_login
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=login
      - POSTGRES_PASSWORD=login
      - POSTGRES_DB=login
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: login
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local